if ($user) {
       if ($user->isActive()) {
             if ($order->hasItems()) {
                   // ...
             } else {
                   // ...
             }
       } else {
             // ...
       }
} else {
       // ...
}