...
// Forever Loop
while(1)
{
		...
    // Free result or a memory leak will occur
    mysql_free_result(result);

		g_force_oscillation.appendMovingAverageData(axis);
		...
} // End forever loop
...